name: skill_branch_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  url_launcher: ^5.4.1
  connectivity: ^0.4.6+2
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  loadmore: ^1.0.4
  flutter_pagewise: ^1.2.3
  logger: ^0.8.3
  shared_preferences: ^0.5.6+1
  image_downloader: ^0.19.1
  kiwi: ^0.2.0

  # redux lib
  built_value:
  built_collection:
  built_redux:
  flutter_built_redux:


  flutter_web_auth:
    path: flutter_web_auth


dev_dependencies:
  flutter_test:
    sdk: flutter

  build:
  build_config:
  built_value_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    # icons
      - assets/icons/like.png
      - assets/icons/maps-and-flags.png
      - assets/icons/group.png
      - assets/icons/bookmark.png
      - assets/icons/home.png
      - assets/icons/feed.png
      - assets/icons/search.png
      - assets/icons/user.png
      - assets/icons/warning.png

    # icons
      - assets/image/connection.png
